# Generated by Django 3.2.7 on 2021-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
