# Generated by Django 3.2.7 on 2021-09-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('version', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model', models.BinaryField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('precision', models.FloatField(null=True)),
                ('recall', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'analyzer',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('key_word', models.CharField(max_length=100, null=True)),
                ('file', models.BinaryField(null=True)),
                ('user_key', models.CharField(max_length=100, null=True)),
                ('results', models.BinaryField(null=True)),
                ('zipped_results', models.BinaryField(null=True)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
